# Generated by Django 5.2.17 on 2026-09-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('no', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('hue', models.IntegerField(default=0)),
                ('blurb', models.TextField(blank=True, default='')),
                ('cover', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['no'],
            },
        ),
    ]
