# Generated by Django 5.2.17 on 2026-09-12 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('hue', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'process_steps',
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('who', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('medium', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('hue', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=1.0)),
                ('featured', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, default='')),
                ('video', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('IN_SALE', 'In Sale'), ('SOLD_OUT', 'Sold Out')], default='IN_SALE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='collections.collection')),
            ],
            options={
                'db_table': 'artworks',
                'ordering': ['-created_at'],
            },
        ),
    ]
